#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Hotfix

#include "Basic.hpp"

#include "Hotfix_classes.hpp"


namespace SDK
{

// Function Hotfix.OnlineHotfixManager.StartHotfixProcess
// (Native, Public, BlueprintCallable)

void UOnlineHotfixManager::StartHotfixProcess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OnlineHotfixManager", "StartHotfixProcess");

	// Hotfix application disabled for dedicated server build to avoid applying potentially
	// incompatible/partial data patches that can leave assets in an invalid state.
	// This makes the server tolerant when remote hotfix data is missing or malformed.
	Log("StartHotfixProcess: hotfix application skipped (disabled).");
	return;
}

}

